services:
  solana-validator:
    build:
      dockerfile: ./Dockerfile.solana-test-validator
      context: .
    image: solana-test-validator:v1.18.26
    ports:
      - '1024:1024' # Gossip port
      - '1027:1027' # TPU port
      - '8899:8899' # JSON RPC port
      - '8900:8900' # WebSocket PubSub port
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H", "Content-Type: application/json", "http://localhost:8899"]
      interval: 5s
      timeout: 10s
      start_period: 15s
      start_interval: 5s
      retries: 10
    command:
    - solana-test-validator
    - --ledger
    - /data

  firehose:
    image: ghcr.io/streamingfast/firehose-solana:v1.1.0
    depends_on:
      solana-validator:
        condition: service_healthy
    restart: on-failure
    ports:
      - '9000:9000' # Substreams tier 1 gRPC port
    entrypoint:
    - /app/firecore
    command:
    - start
    - reader-node,merger,relayer,firehose,substreams-tier1,substreams-tier2
    - --config-file=
    - --log-format=text
    - --log-to-file=false
    - --advertise-chain-name=solana-localnet
    - --common-first-streamable-block=1
    - --reader-node-path=firesol
    - --reader-node-arguments=fetch rpc http://solana-validator:8899 1 --state-dir=./firehose-data/reader/data
    - --substreams-tier1-block-type=sf.solana.type.v1.Block
    - --substreams-tier1-grpc-listen-addr=:9000
